<a href="https://colab.research.google.com/github/eliasdengo/Python-practice-from-beginning-to-advance/blob/Eliasrepos/Car_Price_prediction_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

import that need for our project

In [35]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,r2_score
import matplotlib.pyplot as plt
import seaborn as sns

Loading data

In [36]:
car_data = pd.read_csv('/content/sample_data/car_prediction_data.csv')

In [37]:
print(car_data.head())

  Car_Name  Year  Selling_Price  ...  Seller_Type  Transmission Owner
0     ritz  2014           3.35  ...       Dealer        Manual     0
1      sx4  2013           4.75  ...       Dealer        Manual     0
2     ciaz  2017           7.25  ...       Dealer        Manual     0
3  wagon r  2011           2.85  ...       Dealer        Manual     0
4    swift  2014           4.60  ...       Dealer        Manual     0

[5 rows x 9 columns]

In [38]:
print(car_data.tail())

    Car_Name  Year  Selling_Price  ...  Seller_Type  Transmission Owner
296     city  2016           9.50  ...       Dealer        Manual     0
297     brio  2015           4.00  ...       Dealer        Manual     0
298     city  2009           3.35  ...       Dealer        Manual     0
299     city  2017          11.50  ...       Dealer        Manual     0
300     brio  2016           5.30  ...       Dealer        Manual     0

[5 rows x 9 columns]

In [39]:
#number of column
print(car_data.shape)

(301, 9)

In [40]:
# check null data
car_data.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [41]:
# give details information
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [42]:
# stastical data
car_data.describe()

              Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

Data cleaning and processing

In [43]:

car_data.Transmission.value_counts()

Transmission
Manual       261
Automatic     40
Name: count, dtype: int64

In [44]:
car_data.Seller_Type.value_counts()

Seller_Type
Dealer        195
Individual    106
Name: count, dtype: int64

In [45]:
car_data.Fuel_Type.value_counts()

Fuel_Type
Petrol    239
Diesel     60
CNG         2
Name: count, dtype: int64

ENCODE CATAGOERY BY REPLACE

In [46]:
car_data=car_data.replace({'Fuel_Type':{'Petrol':0,"Diesel":1,"CNG":2},"Seller_Type":{"Dealer":0,"Individual":1},"Transmission":{'Manual':0,"Automatic":1}})

/tmp/ipython-input-3582292352.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  car_data=car_data.replace({'Fuel_Type':{'Petrol':0,"Diesel":1,"CNG":2},"Seller_Type":{"Dealer":0,"Individual":1},"Transmission":{'Manual':0,"Automatic":1}})

In [50]:
car_data.head()

  Car_Name  Year  Selling_Price  ...  Seller_Type  Transmission  Owner
0     ritz  2014           3.35  ...            0             0      0
1      sx4  2013           4.75  ...            0             0      0
2     ciaz  2017           7.25  ...            0             0      0
3  wagon r  2011           2.85  ...            0             0      0
4    swift  2014           4.60  ...            0             0      0

[5 rows x 9 columns]

split train and test data

In [52]:
x =car_data.drop(['Car_Name','Selling_Price'],axis=1)
y =car_data['Selling_Price']

In [54]:
print(x)
print(y)

     Year  Present_Price  Kms_Driven  ...  Seller_Type  Transmission  Owner
0    2014           5.59       27000  ...            0             0      0
1    2013           9.54       43000  ...            0             0      0
2    2017           9.85        6900  ...            0             0      0
3    2011           4.15        5200  ...            0             0      0
4    2014           6.87       42450  ...            0             0      0
..    ...            ...         ...  ...          ...           ...    ...
296  2016          11.60       33988  ...            0             0      0
297  2015           5.90       60000  ...            0             0      0
298  2009          11.00       87934  ...            0             0      0
299  2017          12.50        9000  ...            0             0      0
300  2016           5.90        5464  ...            0             0      0

[301 rows x 7 columns]
0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64

traing and test data size split

In [57]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1,random_state=2)

model Training

In [59]:
linear_car=LinearRegression()

In [62]:
predict_car=linear_car.fit(x_train,y_train)

Model evaluation

In [63]:
prediction_of_car=predict_car.predict(x_train)

In [64]:
print(prediction_of_car)
print(y)

[ 3.73088505e+00  5.60702081e+00  7.79779356e+00 -1.88374756e+00
  6.71614572e+00  8.14343296e+00  5.84067525e+00  6.17919527e+00
  6.15863751e+00  1.59459051e+01  2.15385926e+00  1.11618544e+00
 -4.05463414e-01  6.69051516e+00  6.81961414e+00  1.02957394e+00
  6.74306974e+00  1.43864300e+01  3.00001893e+00  7.95149024e+00
 -8.38569413e-01  9.02067892e+00  1.21210550e+00  2.20040027e+00
 -8.23744275e-01  7.52651502e-01  1.00142469e+01 -4.08950275e-01
 -2.40418357e+00  9.99845989e+00  6.81867179e+00  1.09249928e+00
  4.36158792e+00  9.20660480e-02  3.48993776e+00  2.78147834e+00
  1.50401026e+00  4.65736158e-01  1.68679810e+00  1.18722506e+00
  4.32936153e+00  6.09932798e+00  9.51639926e-01  7.52875828e-01
  6.05967594e+00  3.49453005e+00  2.40969246e+00  7.52230513e+00
  4.63113915e+00  4.44239322e+00  4.22460259e+00  2.71077171e+00
  4.46881874e+00  1.76156730e+00  2.86100050e-01  3.95181249e+00
  1.36371845e+00  4.63046605e+00  1.44343122e+00  7.27550233e+00
  7.26488044e+00  6.54659602e+00  2.36324853e+00  2.19217418e+01
  2.16319930e+00  5.66076848e+00  2.80906060e+00  7.49802869e+00
  5.62886682e+00  9.98314981e+00  2.06830269e+00  2.39461488e+00
  1.25697170e+00  2.48624712e+00  9.87503255e+00  1.99829124e+00
 -5.95850149e-01  5.42977049e+00  1.14801568e+01  7.23519617e-02
  1.16970906e+00  1.59303454e+00  5.41364480e+00  1.41557179e+00
  7.74504567e+00  1.84083793e+01  2.58142127e+00  2.07186281e-01
  1.89736367e+00  9.26780904e+00  3.99021820e+00  7.07156998e+00
  1.68502818e+01  1.02685111e+01  3.68136662e+00  1.50064476e+00
  4.31232923e+00 -4.34880981e-01  1.71285667e+00  8.27991453e+00
  1.14683904e+00  7.50346268e+00 -2.04666325e+00  8.30146254e-01
  7.26854735e+00  8.02021894e+00  7.36905488e+00 -3.79414332e+00
  3.75525897e+00  8.25695012e+00  3.51472306e+00  2.53338755e+00
  4.16232248e+00 -3.24088512e+00  5.18615085e+00  1.85821266e+00
  3.49278787e+00  7.72803450e+00 -2.72911676e-02  1.85585877e+00
  1.61750191e+00  1.86723050e+00  3.44019213e+00 -2.61256990e+00
  2.83571040e-01  6.47077845e+00  6.81795378e+00  1.27856366e+00
  1.98246558e+00  7.77746593e+00  3.99027153e+00  7.11781878e-01
  7.91403394e+00  6.23267855e+00  1.28756708e+00 -1.96729056e+00
  5.28552207e+00  6.04550694e+00  5.16190178e+00  4.22971237e+00
  9.51891054e-01  7.35166727e+00  4.01818932e+00 -1.04710559e+00
  1.09156146e+01  4.39667870e+00  2.86984918e+00  1.91986725e+00
  4.96862623e+00  4.77936928e+00  4.25092177e+00  1.71053421e+01
 -1.07199613e+00  1.26451025e+00  5.21327300e+00  2.12348337e+00
  5.99165891e+00  3.40807255e+00  4.80827934e+00  3.38918116e+00
  5.13795684e-01  4.44055098e+00  2.00903744e+01  3.83901354e+00
  4.53066612e+00  2.19632384e+00  2.97882688e+00  1.63013254e-01
  7.45166142e+00 -9.64114771e-01  2.07084616e+01  1.48302952e-01
  7.67297383e+00  1.97138512e+00  1.58318918e+00  8.59464322e+00
  2.03394215e+01  3.12384360e+00  4.48104068e+00  5.12059119e+00
  4.44820127e+00  6.32711743e+00  6.14313782e+00  1.63379307e+00
  4.86593391e-01  7.15580082e+00  8.19411548e+00  2.20656869e+00
 -3.00310326e+00  4.28862263e+00  4.26053193e+00  5.13714273e+00
 -3.42194582e-01  6.40060227e+00  4.40377318e+00  8.20122236e+00
  8.08394337e-01  1.09158807e+01  5.67433085e+00 -9.84515513e-01
  6.41897928e+00  5.08269665e+00  6.91554730e+00  4.93883063e+00
  5.77578402e+00  2.12723538e+00  2.52675517e+00  4.89440672e+00
  3.15266181e+00 -1.52384175e+00  4.17949082e+01  5.81924561e+00
  5.14055580e+00  3.92237207e-01  9.05432721e+00  6.56459921e+00
  7.18219701e+00  1.66366108e+00  7.11473745e+00  9.07935482e+00
  4.46753893e+00  3.36303450e+00  6.35490979e+00  6.55934903e+00
  1.66016819e+01  9.39027813e+00  6.26564147e+00 -1.43439660e-01
  2.55568656e+00  2.97505284e+00  5.85941753e+00  5.06592497e+00
  9.32375818e-01  8.13064209e+00  5.75158168e+00  7.71554069e+00
  2.18559206e+00  1.67445579e+01  4.87739901e+00  1.46396860e+01
  1.05280516e+01  2.12054166e+00 -5.25492431e-02  9.93653139e+00
 -3.52247643e+00  3.49678260e+00  2.73531683e+00  3.41170538e+00
  7.39379673e+00  3.96888732e+00  1.84083793e+01  8.15712083e+00
  2.54637150e+00  8.78314015e-01  6.36747996e-01  5.77461943e-01
  4.35596477e-01  5.38888735e+00  6.47934817e+00 -3.23943162e-01
  3.10622023e+00  9.01067339e+00  8.42951569e+00  8.19695422e-02
  5.65761124e+00  4.71872253e+00  5.02500936e+00  8.94663115e+00
  8.59464322e+00  3.94153678e-01]
0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 301, dtype: float64