<a href="https://colab.research.google.com/github/eliasdengo/Python-practice-from-beginning-to-advance/blob/Eliasrepos/credit_card_fraud_detection_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

read data from csv file

In [3]:
df = pd.read_csv('/content/sample_data/creditcard.csv')

print data

In [4]:
print(df.head())

   Time        V1        V2        V3        V4        V5        V6        V7  \
0     0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599
1     0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803
2     1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461
3     1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609
4     2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010

        V26       V27       V28  Amount  Class
0 -0.189115  0.133558 -0.021053  149.62    0.0
1  0.125895 -0.008983  0.014724    2.69    0.0
2 -0.139097 -0.055353 -0.059752  378.66    0.0
3 -0.221929  0.062723  0.061458  123.50    0.0
4  0.502292  0.219422  0.215153   69.99    0.0

[5 rows x 31 columns]

In [5]:
print(df.tail())

       Time        V1        V2        V3        V4        V5        V6  \
7968  10980  1.284388 -0.013181  0.646174  0.198985 -0.568675 -0.526121
7969  10981  1.190428 -0.122329  0.954945  0.267101 -0.971026 -0.652279
7970  10981 -0.725175  0.298202  1.824761 -2.587170  0.283605 -0.016617
7971  10981  1.226153 -0.129645  0.735197  0.142752 -0.703245 -0.349641
7972  10981  1.145381 -0.059349  0.968088  0.267891 -0.822582 -0.597727

            V7        V8        V9  ...       V21       V22       V23  \
7968 -0.448235 -0.167709  1.773223  ... -0.101868 -0.030298 -0.081412
7969 -0.612992 -0.003909  1.633117  ... -0.015001  0.127027  0.012079
7970  0.153659  0.045084 -0.197611  ... -0.017097 -0.070535 -0.442861
7971 -0.612641  0.020507  1.648986  ... -0.047936  0.040196 -0.057391
7972 -0.450197 -0.119747  1.338188  ...       NaN       NaN       NaN

           V24       V25       V26       V27       V28  Amount  Class
7968 -0.123281  0.278808  1.064001 -0.090181  0.000481   15.95    0.0
7969  0.534409  0.112179  1.004483 -0.100188 -0.004774   14.95    0.0
7970 -0.895837  0.624743 -0.510601 -0.031142  0.025564   12.95    0.0
7971 -0.012386  0.187685  1.037786 -0.100081 -0.009869   15.95    0.0
7972       NaN       NaN       NaN       NaN       NaN     NaN    NaN

[5 rows x 31 columns]

In [6]:
# i want to get information of data set
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7973 entries, 0 to 7972
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    7973 non-null   int64
 1   V1      7973 non-null   float64
 2   V2      7973 non-null   float64
 3   V3      7973 non-null   float64
 4   V4      7973 non-null   float64
 5   V5      7973 non-null   float64
 6   V6      7973 non-null   float64
 7   V7      7973 non-null   float64
 8   V8      7973 non-null   float64
 9   V9      7973 non-null   float64
 10  V10     7973 non-null   float64
 11  V11     7973 non-null   float64
 12  V12     7973 non-null   float64
 13  V13     7973 non-null   float64
 14  V14     7973 non-null   float64
 15  V15     7972 non-null   float64
 16  V16     7972 non-null   float64
 17  V17     7972 non-null   float64
 18  V18     7972 non-null   float64
 19  V19     7972 non-null   float64
 20  V20     7972 non-null   float64
 21  V21     7972 non-null   float64
 22  V22     7972 non-null   float64
 23  V23     7972 non-null   float64
 24  V24     7972 non-null   float64
 25  V25     7972 non-null   float64
 26  V26     7972 non-null   float64
 27  V27     7972 non-null   float64
 28  V28     7972 non-null   float64
 29  Amount  7972 non-null   float64
 30  Class   7972 non-null   float64
dtypes: float64(30), int64(1)
memory usage: 1.9 MB
None

In [7]:
# i want to describe it
print(df.describe())

               Time           V1           V2           V3           V4  \
count   7973.000000  7973.000000  7973.000000  7973.000000  7973.000000
mean    4257.151261    -0.299740     0.295226     0.899355     0.215736
std     3198.964299     1.498341     1.283914     1.090297     1.447057
min        0.000000   -23.066842   -25.640527   -12.389545    -4.657545
25%     1531.000000    -1.046362    -0.237359     0.372435    -0.687521
50%     3635.000000    -0.416341     0.335446     0.948695     0.223379
75%     6662.000000     1.122758     0.950582     1.597949     1.131542
max    10981.000000     1.685314     8.261750     4.101716     7.380245

                V5           V6           V7           V8           V9  ...  \
count  7973.000000  7973.000000  7973.000000  7973.000000  7973.000000  ...
mean     -0.025285     0.157286    -0.026445    -0.070525     0.655244  ...
std       1.167218     1.325015     1.063709     1.332568     1.156618  ...
min     -32.092129    -7.574798   -12.968670   -23.632502    -3.878658  ...
25%      -0.630525    -0.655399    -0.517733    -0.199794    -0.085635  ...
50%      -0.107337    -0.148669     0.004732     0.016128     0.613170  ...
75%       0.405082     0.555200     0.527353     0.307111     1.294087  ...
max      11.974269    21.393069    34.303177     3.877662    10.392889  ...

               V21          V22          V23          V24          V25  \
count  7972.000000  7972.000000  7972.000000  7972.000000  7972.000000
mean     -0.053715    -0.165799    -0.035174     0.025977     0.088893
std       0.953498     0.654858     0.488322     0.601760     0.427505
min     -11.468435    -8.527145   -15.144340    -2.512377    -2.577363
25%      -0.271837    -0.581473    -0.182989    -0.340419    -0.161009
50%      -0.130344    -0.167048    -0.046107     0.089606     0.115418
75%       0.044823     0.250886     0.086806     0.421015     0.361249
max      22.588989     4.534454    13.876221     3.200201     5.525093

               V26          V27          V28       Amount        Class
count  7972.000000  7972.000000  7972.000000  7972.000000  7972.000000
mean      0.020256     0.016150     0.001161    65.413540     0.003136
std       0.517409     0.403570     0.275976   194.911169     0.055915
min      -1.338556    -7.976100    -3.054085     0.000000     0.000000
25%      -0.363180    -0.063198    -0.019081     4.617500     0.000000
50%      -0.015260     0.007101     0.018443    15.950000     0.000000
75%       0.329322     0.144700     0.080563    54.910000     0.000000
max       3.517346     4.173387     4.860769  7712.430000     1.000000

[8 rows x 31 columns]

In [8]:
# for checking missing data
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [9]:
# distribution of legitmate and fraud transaction
df['Class'].value_counts()

Class
0.0    7947
1.0      25
Name: count, dtype: int64

highly unlabel data set

1.   normal transaction
2.   fraud tansaction

In [12]:
# legit label
legit=df[df.Class==0]

In [13]:
fraud=df[df.Class==1]

In [14]:
legit.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,7947.000000,7947.000000,7947.000000,7947.000000,7947.000000,7947.000000,7947.000000,7947.000000,7947.000000,7947.000000,...,7947.000000,7947.000000,7947.000000,7947.000000,7947.000000,7947.000000,7947.000000,7947.000000,7947.000000,7947.0
mean,4246.546496,-0.297235,0.286979,0.917142,0.201968,-0.023263,0.164019,-0.019547,-0.072779,0.662196,...,-0.055123,-0.165485,-0.034918,0.026636,0.088960,0.019511,0.014875,0.000417,65.284891,0.0
std,3196.114738,1.496782,1.273424,1.038044,1.425650,1.162914,1.319595,1.050472,1.333228,1.149140,...,0.954393,0.655543,0.487537,0.602116,0.422740,0.517724,0.402339,0.275410,194.126547,0.0
min,0.000000,-23.066842,-25.640527,-12.389545,-4.657545,-32.092129,-7.574798,-12.968670,-23.632502,-3.336805,...,-11.468435,-8.527145,-15.144340,-2.512377,-2.577363,-1.338556,-7.976100,-3.054085,0.000000,0.0
25%,1527.500000,-1.045054,-0.241313,0.379656,-0.694284,-0.629111,-0.650819,-0.512667,-0.200028,-0.078339,...,-0.272041,-0.582215,-0.182246,-0.340426,-0.160868,-0.363984,-0.063375,-0.019566,4.795000,0.0
50%,3626.000000,-0.416341,0.332384,0.951058,0.219790,-0.107089,-0.144198,0.005614,0.015552,0.617124,...,-0.130758,-0.166619,-0.046085,0.090637,0.115497,-0.016502,0.006644,0.018351,15.950000,0.0
75%,6618.000000,1.123422,0.943756,1.599386,1.123433,0.404581,0.558822,0.528222,0.303549,1.295309,...,0.043536,0.250886,0.086315,0.421238,0.361021,0.327343,0.142655,0.079781,54.990000,0.0
max,10981.000000,1.685314,8.261750,4.101716,6.825816,11.974269,21.393069,34.303177,3.877662,10.392889,...,22.588989,4.534454,13.876221,3.200201,5.525093,3.517346,4.173387,4.860769,7712.430000,0.0

In [15]:
fraud.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,...,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.0
mean,7359.240000,-1.154048,2.930880,-4.757618,4.590240,-0.636103,-1.952536,-2.202403,0.647916,-1.581984,...,0.393614,-0.265715,-0.116502,-0.183413,0.067479,0.256994,0.421586,0.237600,106.308400,1.0
std,2274.782247,1.768974,1.844817,2.160614,1.622387,2.092747,1.404303,2.352862,0.895666,1.381747,...,0.415540,0.373179,0.703674,0.435323,1.237434,0.335428,0.571243,0.352459,372.676883,0.0
min,406.000000,-4.617217,-3.157307,-7.653616,2.288644,-6.974522,-3.353060,-4.716143,-1.946734,-3.878658,...,-1.052368,-0.932391,-2.119007,-1.632653,-2.032068,-0.657488,-1.002041,-0.900452,0.000000,1.0
25%,7535.000000,-2.312227,2.001485,-5.926130,2.805336,-1.976415,-2.730762,-3.878088,0.133080,-2.770089,...,0.364514,-0.546869,-0.551572,-0.293803,-0.393844,0.304883,0.264028,0.129305,1.000000,1.0
50%,7891.000000,-1.585505,3.261585,-5.234513,4.455923,-0.821628,-2.332285,-3.059245,0.561257,-1.282858,...,0.517232,-0.435901,-0.076584,-0.219845,0.092007,0.323885,0.530507,0.208858,1.000000,1.0
75%,8528.000000,0.329594,4.093912,-4.137422,6.078266,0.973366,-1.706536,-1.496497,1.391657,-0.486097,...,0.645103,0.109541,0.240603,0.083008,1.106766,0.435832,0.620867,0.404474,1.000000,1.0
max,9064.000000,1.234235,5.856393,1.088463,7.380245,3.624201,3.628382,5.431271,1.823233,0.472017,...,0.756053,0.435477,1.375966,0.473246,1.605056,0.566797,1.985913,0.890780,1809.680000,1.0

In [18]:
#to get shaple of legit and fraud
print(legit.shape,fraud.shape)

(7947, 31) (25, 31)

In [21]:
#static amount of the data  of legit and fraud
legit.Amount.describe()

count    7947.000000
mean       65.284891
std       194.126547
min         0.000000
25%         4.795000
50%        15.950000
75%        54.990000
max      7712.430000
Name: Amount, dtype: float64

In [22]:
fraud.Amount.describe()

count      25.000000
mean      106.308400
std       372.676883
min         0.000000
25%         1.000000
50%         1.000000
75%         1.000000
max      1809.680000
Name: Amount, dtype: float64

In [28]:
# from comparission both 0 and 1
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,4246.546496,-0.297235,0.286979,0.917142,0.201968,-0.023263,0.164019,-0.019547,-0.072779,0.662196,...,0.042418,-0.055123,-0.165485,-0.034918,0.026636,0.088960,0.019511,0.014875,0.000417,65.284891
1.0,7359.240000,-1.154048,2.930880,-4.757618,4.590240,-0.636103,-1.952536,-2.202403,0.647916,-1.581984,...,0.263011,0.393614,-0.265715,-0.116502,-0.183413,0.067479,0.256994,0.421586,0.237600,106.308400