<a href="https://colab.research.google.com/github/eliasdengo/Python-practice-from-beginning-to-advance/blob/Eliasrepos/credit_card_fraud_detection_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

read data from csv file

In [ ]:
df = pd.read_csv('/content/sample_data/creditcard.csv')

print data

In [ ]:
print(df.head())

   Time        V1        V2        V3        V4        V5        V6        V7  \
0     0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599
1     0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803
2     1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461
3     1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609
4     2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010

        V26       V27       V28  Amount  Class
0 -0.189115  0.133558 -0.021053  149.62    0.0
1  0.125895 -0.008983  0.014724    2.69    0.0
2 -0.139097 -0.055353 -0.059752  378.66    0.0
3 -0.221929  0.062723  0.061458  123.50    0.0
4  0.502292  0.219422  0.215153   69.99    0.0

[5 rows x 31 columns]

In [ ]:
print(df.tail())

        Time        V1        V2        V3        V4        V5        V6  \
85254  60679  1.258467  0.407363  0.160962  1.034153  0.175374 -0.344634
85255  60680  1.170321 -0.791258  0.341092 -0.498724 -1.234283 -1.024154
85256  60681  0.826449 -0.246364 -0.220287  1.144915  0.119542  0.013537
85257  60682  1.201303 -0.309688 -0.314367  0.167426  1.540306  4.059730
85258  60684 -1.035410  1.278230  1.652904  0.574609 -0.222304  0.410386

             V7        V8        V9  ...       V21       V22       V23  \
85254  0.227623 -0.227186 -0.203630  ... -0.081358 -0.162500 -0.154661
85255 -0.282613 -0.248967 -0.867952  ... -0.577634 -1.495287  0.148887
85256  0.454082 -0.030595 -0.481902  ...  0.142593  0.029994 -0.281769
85257 -1.136824  1.090075  0.760974  ... -0.113604 -0.280918 -0.043147
85258 -0.100852  0.859145 -0.699598  ... -0.104574 -0.408998 -0.128501

            V24       V25       V26       V27       V28  Amount  Class
85254 -0.429501  0.697308 -0.377775  0.027767  0.023488   20.00    0.0
85255  0.380317 -0.089069  0.725803 -0.077233  0.033769  120.99    0.0
85256 -0.287336  0.598513 -0.330393 -0.020391  0.033028  192.00    0.0
85257  1.001217  0.572592 -0.393931  0.074081  0.032089   12.99    0.0
85258 -0.383566  0.099796 -0.432130       NaN       NaN     NaN    NaN

[5 rows x 31 columns]

In [ ]:
# i want to get information of data set
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85259 entries, 0 to 85258
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    85259 non-null  int64
 1   V1      85259 non-null  float64
 2   V2      85259 non-null  float64
 3   V3      85259 non-null  float64
 4   V4      85259 non-null  float64
 5   V5      85259 non-null  float64
 6   V6      85259 non-null  float64
 7   V7      85259 non-null  float64
 8   V8      85259 non-null  float64
 9   V9      85259 non-null  float64
 10  V10     85259 non-null  float64
 11  V11     85259 non-null  float64
 12  V12     85259 non-null  float64
 13  V13     85259 non-null  float64
 14  V14     85259 non-null  float64
 15  V15     85259 non-null  float64
 16  V16     85259 non-null  float64
 17  V17     85259 non-null  float64
 18  V18     85259 non-null  float64
 19  V19     85259 non-null  float64
 20  V20     85259 non-null  float64
 21  V21     85259 non-null  float64
 22  V22     85259 non-null  float64
 23  V23     85259 non-null  float64
 24  V24     85259 non-null  float64
 25  V25     85259 non-null  float64
 26  V26     85259 non-null  float64
 27  V27     85258 non-null  float64
 28  V28     85258 non-null  float64
 29  Amount  85258 non-null  float64
 30  Class   85258 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 20.2 MB
None

In [ ]:
# i want to describe it
print(df.describe())

               Time            V1            V2            V3            V4  \
count  85259.000000  85259.000000  85259.000000  85259.000000  85259.000000
mean   38698.541691     -0.262585     -0.039207      0.679054      0.163611
std    15668.300002      1.878484      1.670189      1.366683      1.363280
min        0.000000    -56.407510    -72.715728    -33.680984     -5.172595
25%    31595.000000     -1.025883     -0.602941      0.184642     -0.722311
50%    41180.000000     -0.258057      0.069615      0.762733      0.186825
75%    50942.000000      1.153099      0.724933      1.390659      1.042062
max    60684.000000      1.960497     18.902453      4.226108     16.715537

                 V5            V6            V7            V8            V9  \
count  85259.000000  85259.000000  85259.000000  85259.000000  85259.000000
mean      -0.277616      0.094861     -0.111651      0.054145     -0.021205
std        1.375170      1.303646      1.237707      1.223035      1.135023
min      -42.147898    -26.160506    -31.764946    -73.216718     -9.283925
25%       -0.896999     -0.644375     -0.603378     -0.140721     -0.690902
50%       -0.311837     -0.155047     -0.072501      0.070103     -0.097017
75%        0.257707      0.488674      0.416990      0.352738      0.602616
max       34.801666     22.529298     36.677268     20.007208     10.392889

       ...           V21           V22           V23           V24  \
count  ...  85259.000000  85259.000000  85259.000000  85259.000000
mean   ...     -0.029273     -0.105613     -0.037762      0.008986
std    ...      0.731860      0.635127      0.626519      0.595040
min    ...    -34.830382    -10.933144    -26.751119     -2.836627
25%    ...     -0.223696     -0.524879     -0.178156     -0.322420
50%    ...     -0.057764     -0.080822     -0.049921      0.064547
75%    ...      0.118290      0.309640      0.080706      0.405794
max    ...     22.614889     10.503090     18.946734      4.014444

                V25           V26           V27           V28        Amount  \
count  85259.000000  85259.000000  85258.000000  85258.000000  85258.000000
mean       0.133598      0.026270      0.001449      0.001934     98.374057
std        0.441017      0.497236      0.389486      0.328312    268.381509
min       -7.495741     -2.534330     -9.390980     -9.617915      0.000000
25%       -0.130610     -0.326403     -0.063467     -0.005899      7.680000
50%        0.171852     -0.072601      0.009302      0.022947     26.990000
75%        0.421184      0.306305      0.082480      0.076063     89.900000
max        5.525093      3.517346     12.152401     33.847808  19656.530000

              Class
count  85258.000000
mean       0.002393
std        0.048857
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000

[8 rows x 31 columns]

In [ ]:
# for checking missing data
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
# distribution of legitmate and fraud transaction
df['Class'].value_counts()

Class
0.0    85054
1.0      204
Name: count, dtype: int64

highly unlabel data set

1.   normal transaction
2.   fraud tansaction

In [ ]:
# legit label
legit=df[df.Class==0]

In [ ]:
fraud=df[df.Class==1]

In [ ]:
legit.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,85054.000000,85054.000000,85054.000000,85054.000000,85054.000000,85054.000000,85054.000000,85054.000000,85054.000000,85054.000000,...,85054.000000,85054.000000,85054.000000,85054.000000,85054.000000,85054.000000,85054.000000,85054.000000,85054.000000,85054.0
mean,38709.224046,-0.247847,-0.049900,0.700980,0.151762,-0.267214,0.099795,-0.095774,0.047207,-0.013915,...,-0.031152,-0.105502,-0.037276,0.009236,0.133378,0.026126,0.000087,0.001840,98.365392,0.0
std,15665.089495,1.817893,1.644577,1.227767,1.335881,1.328207,1.299146,1.152996,1.191201,1.120030,...,0.729165,0.634674,0.622368,0.595228,0.439182,0.497450,0.385013,0.327457,268.470093,0.0
min,0.000000,-56.407510,-72.715728,-33.680984,-5.172595,-42.147898,-26.160506,-31.764946,-73.216718,-6.290730,...,-34.830382,-10.933144,-26.751119,-2.836627,-7.495741,-2.534330,-9.390980,-9.617915,0.000000,0.0
25%,31613.000000,-1.020435,-0.604420,0.189101,-0.724337,-0.893734,-0.641050,-0.600229,-0.140809,-0.686985,...,-0.223825,-0.524682,-0.177768,-0.322273,-0.130324,-0.326513,-0.063566,-0.005887,7.690000,0.0
50%,41185.000000,-0.254475,0.067345,0.765317,0.182134,-0.310637,-0.153446,-0.071105,0.069592,-0.094839,...,-0.058141,-0.080905,-0.049801,0.064615,0.171802,-0.072810,0.009096,0.022897,27.000000,0.0
75%,50945.750000,1.153571,0.719449,1.392415,1.034826,0.258156,0.490627,0.418037,0.350995,0.604993,...,0.117299,0.309492,0.080635,0.405934,0.420978,0.305697,0.081935,0.075733,89.800000,0.0
max,60682.000000,1.960497,18.902453,4.226108,16.715537,34.801666,22.529298,36.677268,18.709255,10.392889,...,22.614889,10.503090,18.946734,4.014444,5.525093,3.517346,12.152401,33.847808,19656.530000,0.0

In [ ]:
fraud.describe()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
count,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,...,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.0
mean,34136.960784,-6.403734,4.412429,-8.467410,5.101621,-4.614515,-1.964040,-6.731357,2.942715,-3.057064,...,0.754409,-0.150411,-0.240026,-0.093307,0.225443,0.088375,0.569295,0.040876,101.986814,1.0
std,16331.645384,7.707640,4.291467,8.283409,2.880670,6.013025,1.533658,6.500479,5.030246,2.486057,...,1.253744,0.803866,1.589648,0.502512,0.930034,0.394222,1.131035,0.584458,229.008970,0.0
min,406.000000,-30.552380,-6.976420,-31.103685,-1.255593,-22.105532,-5.080408,-21.922811,-3.277535,-9.283925,...,-2.475962,-2.288686,-19.254328,-1.632653,-4.781606,-1.055997,-3.908080,-1.869290,0.000000,1.0
25%,20421.250000,-9.957028,1.485631,-13.278066,2.803249,-7.890385,-2.997750,-11.663358,0.091009,-4.576686,...,0.154937,-0.631150,-0.531874,-0.416052,-0.223255,-0.222807,0.061973,-0.128363,1.000000,1.0
50%,36668.500000,-3.302753,3.371708,-5.545624,5.057682,-2.511015,-1.936571,-4.438060,0.900571,-2.776550,...,0.664811,-0.048461,-0.143218,-0.010232,0.194756,0.057055,0.568276,0.188604,7.550000,1.0
75%,45670.000000,-1.091554,6.640090,-2.156527,6.513142,-0.507073,-0.837756,-1.684059,4.019018,-1.203183,...,1.770631,0.374280,0.204436,0.222705,0.719696,0.432297,1.307503,0.403015,99.990000,1.0
max,60353.000000,1.296231,16.713389,2.041003,11.927512,5.269255,3.628382,5.431271,20.007208,2.820829,...,3.147428,1.745315,2.661291,0.795190,2.208209,0.816762,3.052358,1.130625,1809.680000,1.0

In [ ]:
#to get shaple of legit and fraud
print(legit.shape,fraud.shape)

(85054, 31) (204, 31)

In [ ]:
#static amount of the data  of legit and fraud
legit.Amount.describe()

count    85054.000000
mean        98.365392
std        268.470093
min          0.000000
25%          7.690000
50%         27.000000
75%         89.800000
max      19656.530000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     204.000000
mean      101.986814
std       229.008970
min         0.000000
25%         1.000000
50%         7.550000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
# from comparission both 0 and 1
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,38709.224046,-0.247847,-0.049900,0.70098,0.151762,-0.267214,0.099795,-0.095774,0.047207,-0.013915,...,0.041531,-0.031152,-0.105502,-0.037276,0.009236,0.133378,0.026126,0.000087,0.001840,98.365392
1.0,34136.960784,-6.403734,4.412429,-8.46741,5.101621,-4.614515,-1.964040,-6.731357,2.942715,-3.057064,...,0.391757,0.754409,-0.150411,-0.240026,-0.093307,0.225443,0.088375,0.569295,0.040876,101.986814

take sample data

In [ ]:
legit_sample=legit.sample(n=204)

In [ ]:
fraud_sample=fraud.sample(n=204)

merege sample data

In [ ]:
mereged_data=pd.concat([legit_sample,fraud_sample],axis=0)

In [ ]:
mereged_data.shape

(408, 31)

split feature and target data

In [ ]:
x=mereged_data.drop(columns='Class',axis=1)
y=mereged_data['Class']

split data for test and train model

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

In [ ]:
x.shape,x_train.shape,x_test.shape

((408, 30), (326, 30), (82, 30))

train machine learning model

In [ ]:
model=LogisticRegression()

In [ ]:
model.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

model evaluation

In [ ]:
x_train_prediction=model.predict(x_train)

In [ ]:
x_train_prediction_accuracy=accuracy_score(x_train_prediction,y_train)

In [ ]:
print('accuracy on training data',x_train_prediction_accuracy)

accuracy on training data 0.9693251533742331

build predicting system

In [ ]:
# data for prediction
input_data=(1104,-0.423703849876215,0.781511297868078,0.777092317594156,0.680119168578565,0.776653788998222,1.65000548865373,1.19864630654403,-0.0504433338169507,0.236451053028149,0.765075421777556,-0.502256637104945,-0.701779693189264,-1.42550188767144,-0.0983130184356533,-0.108702243259625,-0.598780242853466,-0.398115548810246,0.49732191474271,1.64156050893659,0.380927588693866,-0.257799865458568,-0.0194793100801794,-0.370074938481452,-1.72623145703995,0.0727507844297547,-0.179414134021697,0.237071374308817,-0.238669360890492,106.77)
input_data_as_numpy_array=np.asarray(input_data)
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)

In [ ]:
# predicting for dat
prediction=model.predict(input_data_reshaped)
if(prediction[0]==0):
  print('normal transaction')
else:
  print('fraud transaction')

normal transaction

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(